{
 "title": "Dashboard Smart Home",
 "description": "Energy Optimization Assistant ",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "device",
    "label": "Select appliance",
    "query": {
     "query": "import \"influxdata/influxdb/schema\"\nschema.tagValues(bucket: \"energy_data\", tag: \"device\")"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Actual consumption",
   "type": "gauge",
   "description": "Consumption reported by Wokwi in real time.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"energy_data\")\n  |> range(start: -5m)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"energy_usage\")\n  |> filter(fn: (r) => r[\"_field\"] == \"power\")\n  |> last()"
    }
   ]
  },
  {
   "title": "System Status",
   "type": "stat",
   "description": "A panel that catches if there is a risk of overconsumption detected by AI.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"energy_data\")\n  |> range(start: -5m)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"system_alerts\")\n  |> filter(fn: (r) => r[\"_field\"] == \"alert_active\")\n  |> group(columns: [\"device\"])\n  |> last()"
    }
   ]
  },
  {
   "title": "Prediction Energy Consumption - ${device}",
   "type": "timeseries",
   "description": "Prophet calculates a safety interval (upper_bound and lower_bound).",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "repeat": "device",
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "query": "from(bucket: \"energy_data\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"energy_forecast\")\n  |> filter(fn: (r) => r[\"device\"] == \"${device}\")\n  |> filter(fn: (r) => r[\"_field\"] == \"lower_bound\" or r[\"_field\"] == \"predicted_value\" or r[\"_field\"] == \"upper_bound\")\n  |> yield(name: \"forecast\")"
    }
   ]
  },
  {
   "title": "Switch appliance state",
   "type": "text",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "options": {
    "content": "<div style=\"display: flex; flex-direction: column; gap: 12px; padding: 10px; font-family: sans-serif;\">\n    \n    <div style=\"display: flex; align-items: center; justify-content: space-between; background: rgba(255, 255, 255, 0.05); padding: 10px; border-radius: 6px; border: 1px solid rgba(255, 255, 255, 0.1);\">\n        <span style=\"font-weight: bold; font-size: 13px; color: #d8d9da;\">SONOFF 01</span>\n        <div style=\"display: flex; gap: 8px;\">\n            <a href=\"http://localhost:1880/plug/on?id=sonoff_pow_01\" target=\"hidden_iframe\" \n               style=\"background-color: #2d7e2d; color: white; padding: 6px 16px; text-decoration: none; font-size: 12px; font-weight: bold; border-radius: 4px; display: inline-block;\">ON</a>\n            <a href=\"http://localhost:1880/plug/off?id=sonoff_pow_01\" target=\"hidden_iframe\" \n               style=\"background-color: #a32a2a; color: white; padding: 6px 16px; text-decoration: none; font-size: 12px; font-weight: bold; border-radius: 4px; display: inline-block;\">OFF</a>\n        </div>\n    </div>\n\n    <div style=\"display: flex; align-items: center; justify-content: space-between; background: rgba(255, 255, 255, 0.05); padding: 10px; border-radius: 6px; border: 1px solid rgba(255, 255, 255, 0.1);\">\n        <span style=\"font-weight: bold; font-size: 13px; color: #d8d9da;\">SONOFF 02</span>\n        <div style=\"display: flex; gap: 8px;\">\n            <a href=\"http://localhost:1880/plug/on?id=sonoff_pow_02\" target=\"hidden_iframe\" \n               style=\"background-color: #2d7e2d; color: white; padding: 6px 16px; text-decoration: none; font-size: 12px; font-weight: bold; border-radius: 4px; display: inline-block;\">ON</a>\n            <a href=\"http://localhost:1880/plug/off?id=sonoff_pow_02\" target=\"hidden_iframe\" \n               style=\"background-color: #a32a2a; color: white; padding: 6px 16px; text-decoration: none; font-size: 12px; font-weight: bold; border-radius: 4px; display: inline-block;\">OFF</a>\n        </div>\n    </div>\n    \n</div>"
   }
  },
  {
   "title": "Overconsumption Events",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "query": "from(bucket: \"energy_data\")\n  |> range(start: now(), stop: 6h)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"energy_forecast\")\n  |> filter(fn: (r) => r[\"_field\"] == \"predicted_value\")\n  |> filter(fn: (r) => r[\"_value\"] > 400.0)\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"device\"], valueColumn: \"_value\")\n  |> sort(columns: [\"_time\"], desc: false)"
    }
   ]
  }
 ]
}